### PR TITLE
Theme Edits Grayed Out

### LINKED ISSUE #1657: Theme Edits Grayed Out
# Bug Report

https://wordpress.org/support/topic/theme-edits-grayed-out/

## Expected Behavior

Describe what should happen.

## Actual Behavior

There were suspicious changes made to the functions.php file and when I went to Stream to see who had done it there was nothing there……not even the fix I had just made. So when I went to filter the streams by Theme Edits I notice it is grayed out – there is no option to view those. There is also nowhere in the Settings I can enable it.

Why is this and how can I see that. You would think that would be a major edit admins would want to be able to see

## Steps to Reproduce the Problem

1.
2.
3.

## Screenshots

eRElbJ

## System Information

- Stream plugin version:
- WordPress version:
- PHP version:
- Browser:
- Computer operating system:

### PR DESCRIPTION
**Pull request by marcinkrzeminski**
Fixes #1657

Use alternative hook to track the theme files updates in the Dashboard.

# Checklist

- [ ] Project documentation has been updated to reflect the changes in this pull request, if applicable.
- [x] I have tested the changes in the local development environment (see `contributing.md`).
- [ ] I have added phpunit tests.

## Release Changelog

- Fix Theme files changes are tracked as expected

### CODE REVIEW

File: connectors/class-connector-editor.php [hunk 1]
```diff
@@ -187,33 +186,34 @@ public function action_links( $links, $record ) {
...
 		}
 
 		$plugin_slug = wp_stream_filter_input( INPUT_POST, 'plugin' );
+
 		if ( $plugin_slug ) {
+			$location          = 'plugin-editor.php';
 			$this->edited_file = $this->get_plugin_data( $plugin_slug );
 		}
+
+		$this->log_changes( $location );
```
Comment (tharsheblows) [inline connectors/class-connector-editor.php:216]: **❓question**
If there's no `$location` here, should we log anything? I don't think so?

File: connectors/class-connector-editor.php [hunk 2]
```diff
@@ -187,33 +186,34 @@ public function action_links( $links, $record ) {
...
-				isset( $_SERVER['REQUEST_METHOD'] )
-				&&
-				'POST' !== sanitize_text_field( $_SERVER['REQUEST_METHOD'] )
-			)
-			||
-			'update' !== wp_stream_filter_input( INPUT_POST, 'action' )
-		) {
+		$action         = wp_stream_filter_input( INPUT_POST, 'action' );
+		$request_method = wp_stream_filter_input( INPUT_SERVER, 'REQUEST_METHOD' );
+
```
Comment (tharsheblows) [inline connectors/class-connector-editor.php:196]: **❗️issue**
Can you add a nonce and capability check here? I think it can be the same capability check as is required to do the action.

**Review by tharsheblows — CHANGES_REQUESTED** [review]
A couple of comments but this looks good. I looked it up and the ajax method was added in 4.9 so I think we're safe? It will still work with < WP 4.9 but won't record the changes. 

Should we add a "Requires at least" header? I'm not really sure which version that would be though.

File: connectors/class-connector-editor.php (hunk 1 above)
Comment (marcinkrzeminski) [reply connectors/class-connector-editor.php:232]: Fixed that.

File: connectors/class-connector-editor.php (hunk 2 above)
Comment (marcinkrzeminski) [reply connectors/class-connector-editor.php:211]: Fixed that as well.

**Review by tharsheblows — APPROVED** [review]
Thank you! It all looks good.
