### PR TITLE
Fix dynamic callback method detection

### LINKED ISSUE #1468: Dynamic callback function name cannot include hyphens
# Bug Report

Dynamic callback methods in custom connectors, eg: `callback_ACTION_NAME` cannot have hyphens in their method name, however the callback discovery routine does not convert hyphens to an underscore, hence connectors cannot target actions with hyphens like `load-xxx_xxx` unless they override the `callback` method and target the action manually.

## Expected Behavior

For an action like `load-something`, I should be able to use `callback_load_something` to log that action.

## Actual Behavior

I can't use a dynamic callback to target that action, only way is to override the `callback` method.

## System Information

- Stream plugin version: ALL, including current 3.10.0
- WordPress version: ANY
- PHP version: ANY
- Browser: ANY
- Computer operating system: ANY

### PR DESCRIPTION
**Pull request by shadyvb**
Fixes #1468.

Fixed the dynamic callback locating routine by removing the hyphen as a valid function name character.

# Checklist

- [x] Project documentation has been updated to reflect the changes in this pull request, if applicable.
- [x] I have tested the changes in the local development environment (see `contributing.md`).
- [x] I have added phpunit tests.

## Release Changelog

- Fix: Fixed the dynamic callback locating routine by removing the hyphen as a valid function name character.

## Release Checklist

- [x] This pull request is to the `master` branch.
- [x] Release version follows [semantic versioning](https://semver.org). Does it include breaking changes?
- [x] Update changelog in `readme.txt`.
- [x] Bump version in `stream.php`.
- [x] Bump `Stable tag` in `readme.txt`.
- [x] Bump version in `classes/class-plugin.php`.
- [ ] Draft a release [on GitHub](https://github.com/xwp/stream/releases/new).

### CODE REVIEW

File: classes/class-plugin.php [hunk 1]
```diff
@@ -18,7 +18,7 @@ class Plugin {
 	 *
 	 * @const string
 	 */
-	const VERSION = '3.10.0';
+	const VERSION = '3.10.1';
```
Comment (delawski) [inline classes/class-plugin.php:21]: **🧹 chore:** Let's not bump the version number just yet. This update will be part of `4.0.1` release and we're going to set the plugin version there, just before releasing.

```suggestion
	const VERSION = '3.10.0';
```

File: readme.txt [hunk 2]
```diff
@@ -3,7 +3,7 @@ Contributors: xwp
 Tags: wp stream, stream, activity, logs, track
 Requires at least: 4.5
 Tested up to: 6.3
-Stable tag: 3.10.0
+Stable tag: 3.10.1
```
Comment (delawski) [inline readme.txt:6]: **🧹 chore:** Let's not bump the version number just yet. This update will be part of `4.0.1` release and we're going to set the plugin version there, just before releasing.

```suggestion
Stable tag: 3.10.0
```

File: readme.txt [hunk 3]
```diff
@@ -103,6 +103,10 @@ Track changes to posts when using the block editor.
 
 == Changelog ==
 
+= 3.10.1 - October 9, 2023 =
+
+- Fix: Fixed the dynamic callback locating routine by removing the hyphen as a valid function name character.
+
```
Comment (delawski) [inline readme.txt:109]: **🧹 chore:** As above, this will be done as part of `4.0.1` release.

```suggestion
```

File: stream.php [hunk 4]
```diff
@@ -3,7 +3,7 @@
  * Plugin Name: Stream
  * Plugin URI: https://xwp.co/work/stream/
  * Description: Stream tracks logged-in user activity so you can monitor every change made on your WordPress site in beautifully organized detail. All activity is organized by context, action and IP address for easy filtering. Developers can extend Stream with custom connectors to log any kind of action.
- * Version: 3.10.0
+ * Version: 3.10.1
```
Comment (delawski) [inline stream.php:6]: **🧹 chore:** As above, this will be done as part of 4.0.1 release.

```suggestion
 * Version: 3.10.0
```

**Review by delawski — CHANGES_REQUESTED** [review]
@shadyvb Thanks for that fix 🙌 

I've changed the target branch to `develop` since we'd like to release this update as part of the upcoming `4.0.1` release. All of my comments are just about that. I'll try to address them myself, directly in GitHub, so that we're clear right away.

**Review by delawski — APPROVED** [review]

File: tests/tests/test-class-connector.php [hunk 5]
```diff
@@ -27,6 +27,7 @@ public function setUp(): void {
 			 */
 			public $actions = array(
 				'simulate_fault',
+        'hyphenated-action',
```
Comment (delawski) [inline tests/tests/test-class-connector.php:30]:
```suggestion
				'simulate_fault',
				'hyphenated-action',
```

File: tests/tests/test-class-connector.php [hunk 6]
```diff
@@ -69,6 +70,17 @@ public function callback_simulate_fault() {
...
+      /**
+       * Log the hyphenated action callback.
+       *
+       * @action hyphenated-action
+       *
+       * @return void
+       */
+      public function callback_hyphenated_action() {
+				do_action( 'wp_stream_test_child_callback_hyphenated_action' );
+      }
```
Comment (delawski) [inline tests/tests/test-class-connector.php:83]:
```suggestion
			}

			/**
			* Log the hyphenated action callback.
			*
			* @action hyphenated-action
			*
			* @return void
			*/
			public function callback_hyphenated_action() {
				do_action( 'wp_stream_test_child_callback_hyphenated_action' );
			}
```

File: tests/tests/test-class-connector.php [hunk 7]
```diff
@@ -236,6 +259,7 @@ public function test_is_dependency_satisfied() {
 		$this->assertTrue( $this->connector->is_dependency_satisfied() );
 	}
 
+
```
Comment (delawski) [inline tests/tests/test-class-connector.php:262]:
```suggestion
```

**Review by delawski — COMMENTED** [review]
Cleanup after resolving merge conflicts with `develop` directly in GH.

**Comment by delawski** [comment]
The [Lint and Test task succeeded](https://github.com/shadyvb/wp-stream/actions/runs/10039945093/job/27744938609) so I'm merging the PR to `develop` now. Thanks again, @shadyvb!
