### PR TITLE
Add custom JS to fix select all toggle on alerts list

### LINKED ISSUE #1661: Select all alerts in table view not working
# Bug Report

## Expected Behavior

It's expected that select all checkbox selects each row.

## Actual Behavior

When clicking on the select all checkbox none of the rows are selected.

## Steps to Reproduce the Problem

1. Go to alerts.
2. Click on the select all checkbox (you need to have at least one alert created).

## Screenshots

https://github.com/user-attachments/assets/e73f9537-9b22-479a-9b47-103a962050df

## System Information

- Stream plugin version: 4.0.2
- WordPress version: 6.7.1
- PHP version: 7.4.33
- Browser: Arc (Chromium) Version 1.74.0 (57065), Chromium Engine Version 131.0.6778.205
- Computer operating system: macOS 15.2 (24C101)

### PR DESCRIPTION
**Pull request by marcinkrzeminski**
Fixes #1661

It turned the `inline-edit-post` script which is a dependency for `wp-stream-alerts` has a `tags-suggest` as a dependency which was causing issues with select all on the Alerts list screen. The solution was to deregister that script on that screen.

# Checklist

- [ ] Project documentation has been updated to reflect the changes in this pull request, if applicable.
- [x] I have tested the changes in the local development environment (see `contributing.md`).
- [ ] I have added phpunit tests.

## Release Changelog

- Fix Select all on the Alerts list screen

### CODE REVIEW

File: classes/class-alerts-list.php [hunk 1]
```diff
@@ -338,6 +338,12 @@ public function enqueue_scripts() {
 			return;
 		}
 
+		/**
+		 * Remove the WP core tags - suggest script on the alerts list screen.
+		 * This is not needed, but more importantly it was breaking the select all functionality.
+		 */
+		wp_deregister_script( 'tags-suggest' );
```
Comment (tharsheblows) [inline classes/class-alerts-list.php:345]: **❗️issue**
This causes the Alerts screen to not work for me. Which version of WP are you on? I've tested on 6.7.1 and 6.6.2.

**Review by tharsheblows — CHANGES_REQUESTED** [review]

File: classes/class-alerts-list.php (hunk 1 above)
Comment (marcinkrzeminski) [reply classes/class-alerts-list.php]: OMG, great catch 🤦🏻‍♂️. I have reverted that and added a few lines of JS to re-enable the select all toggle.

**Review by tharsheblows — COMMENTED** [review]
@marcinkrzeminski I think some extra files have gotten in. This is working for me now but those files should probably be removed.

**Review by tharsheblows — APPROVED** [review]
@marcinkrzeminski This looks good, thank you! There's a merge conflict but after that's resolved it's good to go.
